config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as:"about"
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
 
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         validates :name, uniqueness: true, length: { in: 2..20 }
         validates :introduction, length: { maximum: 50 }
         
         has_many :favorites, dependent: :destroy
         has_many :books, dependent: :destroy
         has_many :book_comments, dependent: :destroy
          has_one_attached :profile_image
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
     root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book.id)
  end
  
  def destroy
     BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def  create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
   if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
   else
      @user = current_user
      @books = Book.all
      render :index
   end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end
  

  def edit
     @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(books_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
       render :edit
    end
  end


  private

  def books_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to books_path unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path
   else
     render :edit
   end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

  def correct_user
     @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
 <h2>User info</h2>

  <table class="table">
    <tbody>
      <tr><%= image_tag user.get_profile_image(100,100) %></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>

    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
    </div>
    <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved: %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
      
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title,class:'form-control' %>
      </div>
      
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body,class:'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.submit'Update Book', class:"btn btn-success" %>
      </div>
      
      <% end %>
      
      <%= link_to"Show", book_path(@book) %> |
      <a href="/books">Back</a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<p><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render'book',{ user: @user, book: @book } %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
           <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <% image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book),class:'text-danger', method: :delete do %>
                      <i class="fas fa-heart"></i><%= "#{book.favorites.count}" %>
                    <% end %>
                <% else %>
                    <%= link_to book_favorites_path(book),class:'text-primary', method: :post do %>
                       <i class="fas fa-heart"></i><%= "#{book.favorites.count}" %>
                    <% end %>
                <% end %>
              </td>
              <td><%= "コメント数:#{book.book_comments.count}" %></td>
            </tr>
           <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p><%= flash[:notice] %></p>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render'book',{ user: @book.user,  book: @book_new } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
              <%= image_tag @book.user.get_profile_image(60,60) %><br><%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td>
              <%= @book.body %>
            </td>

            <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class:'btn btn-sm btn-success'%>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "date-confirm" => "本当に消しますか？", class:'btn btn-sm btn-danger' %>
              </td>
            <% end %>
             <td>
               <% if @book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(@book),class:'text-danger', method: :delete do %>
                      <i class="fas fa-heart"></i><%= "#{@book.favorites.count}" %>
                    <% end %>
                <% else %>
                    <%= link_to book_favorites_path(@book),class:'text-primary', method: :post do %>
                       <i class="fas fa-heart"></i><%= "#{@book.favorites.count}" %>
                    <% end %>
                <% end %>
             </td>
              <td>
                <td>コメント件数：<%= @book.book_comments.count %></td>
              </td>
          </tr>
        </tbody>
      </table>
       <% @book.book_comments.each do |book_comment| %>
       <p> 
       <%= image_tag book_comment.user.get_profile_image(70,70) %>
       <%= book_comment.user.name %>
       <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment),class:'btn btn-sm btn-danger', method: :delete %>
        <br><%= link_to book_comment.user.name,user_path(book_comment.user.id) %>
        <% end %>
      </p>
      <% end %>
            <%= form_with model: [@book,@book_comment] do |f| %>
             <%= f.text_area :comment, rows: '5' %>
              <%= f.submit "送信する" %>
          　 <% end %>
    </div>
  </div>
</div>

<div>

app/views/homes/about.html.erb
<p><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">"Welcome to"<i class="fas fa-book"></i><strong>Bookers</strong>"!"</h1>
  </div>
</div>

app/views/homes/top.html.erb
<p><%= flash[:notice] %></p>

  <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
          <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
          <p>you can share and exchange your opinions , inpressions , and emotions</p>
          <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
         
              <%= link_to "Log in", new_user_session_path, class:'btn btn-info btn-sm btn-block mb-3' %>

              <%= link_to "Sign up", new_user_registration_path, class:'btn btn-success btn-sm btn-block mb-3' %>
              
          </div>
        </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

       <div class="container">

      <span><%= link_to"Bookers", root_path, class:'navbar-brand' %></span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
          
          <li>
            <%= link_to user_path(current_user), class:'nav-link text-light' do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          
          <li>
            <%= link_to users_path, class:'nav-link text-light' do %>
              <i class="fas fa-users"></i>Users
            <% end %>
          </li>
           
          <li>
            <%= link_to books_path, class:'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>Books
            <% end %>
          </li>
          
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>logout
            <% end %>
          </li>
       
        <% else %>
           
            <li>
              <%= link_to root_path, class:'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            
            <li>
              <%= link_to about_path, class:'nav-link text-light' do %>
                 <i class="fas fa-link"></i>About
              <% end %>
            </li>
             
             <li>
             <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
               <i class="fas fa-user-plus"></i>sign up
             <% end %>
            </li>
            
            <li>
             <%= link_to new_user_session_path, class:'nav-link text-light' do %>
               <i class="fas fa-sign-in-alt"></i>login
             <% end %>
            </li>  
        <% end %>
          </li>
         </ul>
       </ul>
      </div>
     </div>
    </nav>

  </header>

  <main>
    <%= yield %>
  </main>

<footer>
  <div class="container mt-5">
   <div class="row">
    <div class="mx-auto">
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
</footer>

 </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved: %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<p><%= flash[:notice] %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      
      <%= form_with model: @user do |f| %>
      
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", class:'form-control name' %>
      </div>
      
      <div class="form-group">
         <label for="user_profile_image">Image</label>
        <%= f.file_field :profile_image, accept: "image/*", class:'form-control-file user_image' %>
      </div>
      
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, autofocus: true,  id:"Introduction", class:'form-control introduction' %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Update User", class:'btn btn-secondary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
  <p><%= flash[:notice] %></p>
  
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render'books/book',{user: @user,book: @book} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
           <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to"Show", user_path(user.id) %></td>
            </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p><%= flash[:notice] %></p>

 <div class="container px-5 px-sm-0">
   <div class="row">
     <div class="col-md-3">
       <%= render'books/book',{user: @user,book: @book} %>
     </div>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        <tbody>
        <% @books.each do |book| %>
          <tr>

            <td>
             <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
            </td>

            <td><%= link_to book.title, book_path(book) %></td>

            <td><%= book.body %></td>
            <td>
            <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book),class:'text-danger', method: :delete do %>
                      <i class="fas fa-heart"></i><%= "#{book.favorites.count}" %>
                    <% end %>
                <% else %>
                    <%= link_to book_favorites_path(book),class:'text-primary', method: :post do %>
                       <i class="fas fa-heart"></i><%= "#{book.favorites.count}" %>
                    <% end %>
          <% end %>
              </td>
              <td><%= "コメント数:#{book.book_comments.count}" %></td>
          </tr>
        <% end %>
        </tbody>
       </thead>
      </table>
     </div>
 </div>
</div>